import { ProjectType } from "./src/types";
export const projects: ProjectType[] = [
  {
    id: 1,
    name: "Tuition Terminal",
    description: "My first portfolio website",
    gitLink: null,
    imageLink: "https://i.postimg.cc/8PH32G8M/tterminal.png",
    liveLink: "https://tuitionterminal.com.bd/",
    workDuration: "1 week",
    tags: ["react", "javascript", "vite", "bootstrap5", "redux"],
  },
  {
    id: 2,
    name: "Porao",
    description: "My first portfolio website",
    gitLink: null,
    imageLink: "https://i.postimg.cc/Hx68GjtF/tterminal-1.png",
    liveLink: "https://porao.com.bd",
    workDuration: "1 week",
    tags: [
      "react",
      "typescript",
      "vite",
      "tailwindcss",
      "react-query",
      "zustand",
    ],
  },
  {
    id: 3,
    name: "Taiuun",
    description: "My first portfolio website",
    gitLink: null,
    imageLink: "https://i.postimg.cc/m2Kn7d1Y/taiuun-job-hunting.png",
    liveLink: null,
    workDuration: "1 week",
    tags: ["react", "javascript", "vite", "tailwindcss", "nextjs", "redux"],
  },
  {
    id: 4,
    name: "Shinabe Design",
    description: "My first portfolio website",
    gitLink: null,
    imageLink: "https://i.postimg.cc/1XtwXj60/tterminal.png",
    liveLink: "https://projectdev2024.vercel.app",
    workDuration: "1 week",
    tags: ["tailwindcss", "react", "vite"],
  },
];
